export default function Label({ ...props }) {
  const dict = {
    application_type:"এপ্লিকেশন টাইপ ",
    certificate_type:"সনদের ধরণ ",
    name: "নাম",
    name_eng:"নাম (ইংরেজি)",
    phone: "মোবাইল নম্বর",
    email: "ইমেইল",
    email_verified_at:"ইমেইল যাচাই",
    nid: "এনআইডি",
    capacity:"ক্যাপাসিটি",
    candidate:"ক্যান্ডিডেট",
    contact:"যোগাযোগকারী",
    contact_person:"যোগাযোগকারী ব্যক্তি",
    contact_person_bn:"যোগাযোগকারী ব্যক্তি বাংলায় ",
    contact_person_email:"যোগাযোগকারী ব্যক্তির ইমেল",
    contact_person_number:"যোগাযোগকারী ব্যক্তির ফোন",
    contact_person_position:"যোগাযোগকারী ব্যক্তির পদবী",
    course_name_bn:"কোর্সের নাম বাংলায় ",
    course_name_eng:"কোর্সের নাম ",
    course_fee:'প্রশিক্ষণ খরচ',
    exam_date:"পরীক্ষার তারিখ",
    edu_qualification_no:'সনদের  নম্বর',
    description_bn:"বর্ণনা",
    dos_fee:'ডস ফি',
    duration_year:"সময়কাল",
    username: "ইউজার আইডি",
    update_counter: "আপডেট কাউন্টার",
    invoice:"ইনভয়েস",
    institute: "প্রশিক্ষণ কেন্দ্রের নাম",
    bin_number: "বিন নম্বর",
    total_payment:"টোটাল পেমেন্ট (টাকা) ",
    tin_number: "টিন নম্বর",
    trainer_type:"ট্রেনার টাইপ",
    trainer_grade:"ট্রেনার যোগ্যতা সনদের  গ্রেড",
    trainer_status:"ট্রেনার স্টেটাস",
    trade_license_no: "ট্রেড লাইসেন্স নম্বর",
    dos_noc_no:"এনওসি নম্বর",
    tenancy_agreement_date:"ট্যানেন্সি চুক্তির তারিখ",
    approval_date:"অনুমোদনের তারিখ",
    last_audit_date:"শেষ অডিট তারিখ",
    institute_type:"ইনস্টিটিউটের ধরন",
    update:"আপডেট",
    payment:'পেমেন্ট',
    premise:"প্রিমিস",
    principal:"অধ্যক্ষ",
    principal_bn:" অধ্যক্ষের নাম বাংলায়",
    principal_email:"অধ্যক্ষের ইমেইল",
    principal_mobile:"অধ্যক্ষের মোবাইল",
    start_date:"শুরুর তারিখ",
    start_time:"শুরুর সময়",
    end_time:"শেষ সময়",
    end_date:"শেষ তারিখ",
    update_date:"আপডেট তারিখ",
    created:"তৈরি",
    vat:'ভ্যাট',
    dob : 'জন্মতারিখ',
    address1 : 'ঠিকানা ১',
    address2 : 'ঠিকানা ২',
    batch_no : 'ব্যাচ নম্বর',
    batch_name : 'ব্যাচের নাম',
    address3 : 'ঠিকানা ৩',
    application_status : 'অ্যাপ্লিকেশান স্ট্যাটাস',
    payment_status :"পেমেন্ট স্ট্যাটাস",
    apply_for : "প্রসেস স্ট্যাটাস",
    position : "অবস্থান",
    max_candidate : "সর্বোচ্চ ক্যান্ডিডেট",
    icn : "আইসিএন"
  };

  return <label  {...props}>{dict[props.value]}</label>;
}
